import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html  lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased font-sans text-zinc-900 dark:text-zinc-50`}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
